import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";

/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 */

export const users = [
  {
    _id: uuid(),
    firstName: "Guest",
    lastName: "User",
    username: "guestuser",
    password: "guest123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    profileAvatar: "https://picsum.photos/200/200",
    bio: "Exploring the platform as a guest user. Here to experience the magic without signing up!",
    website: "https://example.com",
  followers: [],
  following: [],
    background: "https://res.cloudinary.com/dazdakg1z/image/upload/v1684863377/samples/people/nature.jpg",
  },
  {
    _id: uuid(),
    firstName: "Alex",
    lastName: "Johnson",
    username: "alexj",
    email: "alex.johnson@example.com",
    password: "alex123",
    bio: "Tech enthusiast and blogger",
    profileAvatar: "https://source.unsplash.com/random/200x200/?person",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    website: "https://example.com",
    followers: [],
    following: [],
    background: "https://res.cloudinary.com/dazdakg1z/image/upload/v1684863377/samples/people/nature.jpg",
  },
  {
    _id: uuid(),
    firstName: "Mia",
    lastName: "Patel",
    username: "miap",
    email: "mia.patel@example.com",
    password: "mia123",
    bio: "Lover of coffee and coding",
    profileAvatar: "https://source.unsplash.com/random/200x200/?woman",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    website: "https://example.com",
    followers: [],
    following: [],
    background: "https://res.cloudinary.com/dazdakg1z/image/upload/v1684863377/samples/people/nature.jpg",
  },
  {
    _id: uuid(),
    firstName: "Liam",
    lastName: "Wong",
    username: "liamw",
    email: "liam.wong@example.com",
    password: "liam123",
    bio: "Photographer and traveler",
    profileAvatar: "https://source.unsplash.com/random/200x200/?man",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    website: "https://example.com",
    followers: [],
    following: [],
    background: "https://res.cloudinary.com/dazdakg1z/image/upload/v1684863377/samples/people/nature.jpg",
  },
  {
    _id: uuid(),
    firstName: "Sofia",
    lastName: "Martinez",
    username: "sofia_m",
    email: "sofia.martinez@example.com",
    password: "sofia123",
    bio: "Foodie and adventure seeker",
    profileAvatar: "https://source.unsplash.com/random/200x200/?woman,smile",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    website: "https://example.com",
    followers: [],
    following: [],
    background: "https://res.cloudinary.com/dazdakg1z/image/upload/v1684863377/samples/people/nature.jpg",
  },
  {
    _id: uuid(),
    firstName: "Daniel",
    lastName: "Kim",
    username: "danielk",
    email: "daniel.kim@example.com",
    password: "daniel123",
    bio: "Fitness coach and marathon runner",
    profileAvatar: "https://source.unsplash.com/random/200x200/?man,fitness",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    website: "https://example.com",
    followers: [],
    following: [],
    background: "https://res.cloudinary.com/dazdakg1z/image/upload/v1684863377/samples/people/nature.jpg",
  }
]
